name: appwrite_auth_kit
description: A wrapper for Appwrite's Accounts service, makes it easy to manage authentication and account features.
version: 0.9.0
homepage: https://github.com/lohanidamodar/appwrite_auth_kit

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  appwrite: ^11.0.0
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null

